### ISSUE TITLE
Error while gathering data

### ISSUE THREAD

**Issue by mmarlow** [dirkjanm/ROADtools#17]
Hi! 
Attempting to run roadrecon gather -t xxxx python 3.9.0 on Windows 10. I get multiple exceptions of the same type.  First two are shown below.  Any fix or suggestion would be greatly appreciated!

(venv) D:\tools\az-tools>roadrecon gather -t <tenant id>
Starting data gathering phase 1 of 2 (collecting objects)
Starting data gathering phase 2 of 2 (collecting properties and relationships)
ROADrecon gather executed in 13.50 seconds and issued 1181 HTTP requests.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000177675B7A60>
Traceback (most recent call last):
  File "c:\python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "c:\python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "c:\python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "c:\python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000177675B7A60>
Traceback (most recent call last):
  File "c:\python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "c:\python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "c:\python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "c:\python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by dirkjanm** [comment]
this is a strange artifact but not an error, the gathering already completed with success, see also #15 
you should be able to continue viewing the data without issue

**Comment by dirkjanm** [comment]
this should be fixed with the latest version on master
