### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER when sending roadrecon traffic via Burp

### ISSUE THREAD

**Issue by pawp81** [dirkjanm/ROADtools#18]
Windows machine proxy settings are configured to use Burp. 
```
C:\utilities\ROAD>netsh winhttp show proxy

Current WinHTTP proxy settings:

    Proxy Server(s) :  192.168.0.80:8080
    Bypass List     :  (none)
```

Burp works fine with TLS traffic sent from other clients (web browser, Outlook)
However when running roadrecon to obtain nonce following SSL error is returned. What is interesting is that on Burp I see response from login.microsoftonline.com with nonce.
Does Burp need to be configured in a specific way or is python's request module fault?
```
C:\utilities\ROAD>roadrecon auth --prt-init
Traceback (most recent call last):
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\urllib3\connection.py", line 496, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /Common/oauth2/authorize?resource=https%3A%2F%2Fgraph.windows.net%2F&client_id=1b730954-1685-4b74-9bfd-dac224a7b894&response_type=code&haschrome=1&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&client-request-id=97270c27-da1d-4fe9-9659-ff5ad9bcefeb&x-client-SKU=PCL.Desktop&x-client-Ver=3.19.7.16602&x-client-CPU=x64&x-client-OS=Microsoft+Windows+NT+10.0.19569.0&site_id=501358&mscrid=361e6c6a-b91c-4965-ad6b-fbfef26fb518 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\johndoe\AppData\Local\Programs\Python\Python39\Scripts\roadrecon-script.py", line 33, in <module>
    sys.exit(load_entry_point('roadrecon==0.9.0', 'console_scripts', 'roadrecon')())
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\roadtools\roadrecon\main.py", line 106, in main
    res = auth.get_tokens(args)
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\roadtools\roadlib\auth.py", line 372, in get_tokens
    nonce = self.get_prt_cookie_nonce()
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\roadtools\roadlib\auth.py", line 143, in get_prt_cookie_nonce
    res = ses.get('https://login.microsoftonline.com/Common/oauth2/authorize', params=params, headers=headers, allow_redirects=False)
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\johndoe\appdata\local\programs\python\python39\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /Common/oauth2/authorize?resource=https%3A%2F%2Fgraph.windows.net%2F&client_id=1b730954-1685-4b74-9bfd-dac224a7b894&response_type=code&haschrome=1&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&client-request-id=97270c27-da1d-4fe9-9659-ff5ad9bcefeb&x-client-SKU=PCL.Desktop&x-client-Ver=3.19.7.16602&x-client-CPU=x64&x-client-OS=Microsoft+Windows+NT+10.0.19569.0&site_id=501358&mscrid=361e6c6a-b91c-4965-ad6b-fbfef26fb518 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))
```

**Comment by dirkjanm** [comment]
I'm not sure whether python on Windows respects the netsh proxy settings. Currently specifying a proxy is only sort of supported in the authentication phase, but it is not used in all requests so it's not super useful.
You could add 
```
self.proxies = {
  'http': 'http://127.0.0.1:8080',
  'https': 'http://127.0.0.1:8080',
}
```

here: https://github.com/dirkjanm/ROADtools/blob/4a8cd6c0d5074e57d57efdb61746b9958636a721/roadlib/roadtools/roadlib/auth.py#L32
and then set
 ```
self.verify = False
```
on the next line to accept all certificates.

Just to reiterate: this will only proxy some authentication requests through the proxy, and will not proxy any of the gathering commands.

**Comment by pawp81** [comment]
Internet explorer proxy settings are enough to send python traffic through proxy. I see the traffic in Burp when I configure them.
Actually setting self.proxies and self.verify doesn't seem to change anything. If I configure them without inet proxy settings nothing is set to Burp. If I configure inet proxy, but leave self.proxies empty, I see traffic on the web proxy. However there is SSL: WRONG_VERSION_NUMBER error.

**Comment by pawp81** [comment]
The solution was to downgrade urllib3 to 1.23 and to add Burp's certificate to: 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\certifi\\cacert.pem'
https://www.programmersought.com/article/34366214760/
