### ISSUE TITLE
error during "gui" - missing index.html

### ISSUE THREAD

**Issue by jurajsucik** [dirkjanm/ROADtools#24]
I am getting this error during the roadrecon gui. It seems like ROADtools/roadrecon/roadtools/roadrecon/dist_gui/index.htm is missing:

 * Serving Flask app "roadtools.roadrecon.server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2021-02-12 08:49:06,680] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Do_Not_Scan/repos/ROADtools/roadrecon/roadtools/roadrecon/server.py", line 154, in get_index
    return send_file('dist_gui/index.html')
  File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 629, in send_file
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Do_Not_Scan/repos/ROADtools/roadrecon/roadtools/roadrecon/dist_gui/index.html'
127.0.0.1 - - [12/Feb/2021 08:49:06] "GET / HTTP/1.1" 500 -

**Comment by dirkjanm** [comment]
If you clone the tool from GitHub the GUI files are missing, they can be downloaded from the azure pipeline builds as stated in the readme, or you can install npm and angular and build the files in dev mode.
