### ISSUE TITLE
[bug] OverflowError: mktime argument out of range

### ISSUE THREAD

**Issue by mgeeky** [dirkjanm/ROADtools#34]
Hi!

When working on a huge database (2,5GB+, the same one mentioned in the previous issue) I've stumbled upon the following exception:

```
127.0.0.1 - - [17/Jan/2022 02:17:57] "GET /api/oauth2permissions HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Python310\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python310\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python310\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python310\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python310\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python310\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python310\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python310\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python310\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python310\Lib\site-packages\roadtools\roadrecon\server.py", line 337, in get_oauth2permissions
    return jsonify(oauth2permissions)
  File "C:\Python310\Lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Python310\Lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Python310\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python310\Lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Python310\Lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "C:\Python310\Lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "C:\Python310\Lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Python310\Lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Python310\Lib\site-packages\flask\json\__init__.py", line 91, in default
    return http_date(o.utctimetuple())
  File "C:\Python310\Lib\site-packages\werkzeug\http.py", line 995, in http_date
    timestamp = mktime(timestamp)
OverflowError: mktime argument out of range
```

My initial guess is that there might be some discrepancies between various timestamp formats (when collected from a huge Azure deployment). The question is, can we do anything about the pulled data's model consistency?

Or maybe the error is just simply result of overly-enormous data collection fed to the JSON serializer? Causing enormous RAM consumption and crashing serializer in a process? Have no idea...

Regards,
Mariusz.

**Comment by dirkjanm** [comment]
It's in the `get_oauth2permissions` function, which should not have such a large amount of records. I guess this oauth2permission object is corrupted somehow which makes it fail to convert to JSON. I can't really do much about this without knowing which exact record fails and why. Even then the conversion is many libraries deep outside of roadrecon so it would be complex to fix.

**Comment by mgeeky** [comment]
Agree, I have no clue how to further troubleshoot that one and how to provide you with more concrete data to work with. Will try to hack around my roadtools.db when I find spare time though.
