### ISSUE TITLE
[bug] MFA policies dump crashed with KeyError: KnownNetworkPolicies

### ISSUE THREAD

**Issue by mgeeky** [dirkjanm/ROADtools#37]
Hi there Jan!

Yet another bug found while trying to dump MFA policies via plugin. It started smoothly by enumerating first two correctly but then crashed:

```
PS> roadrecon plugin policies -d .\roadrecon3.db -p
```

```
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\studentuser24\.virtualenvs\ROADTools-iANiAUBN\Scripts\roadrecon.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\.virtualenvs\roadtools-ianiaubn\lib\site-packages\roadtools\roadrecon\main.py", line 123, in main
    plugin_module.main(args)
  File "c:\users\administrator\.virtualenvs\roadtools-ianiaubn\lib\site-packages\roadtools\roadrecon\plugins\policies.py", line 395, in main
    plugin.main(args.print)
  File "c:\users\administrator\.virtualenvs\roadtools-ianiaubn\lib\site-packages\roadtools\roadrecon\plugins\policies.py", line 346, in main
    out['locations'] = self._parse_locations(conditions)
  File "c:\users\administrator\.virtualenvs\roadtools-ianiaubn\lib\site-packages\roadtools\roadrecon\plugins\policies.py", line 236, in _parse_locations
    ot += self._parse_locationcrit(icrit)
  File "c:\users\administrator\.virtualenvs\roadtools-ianiaubn\lib\site-packages\roadtools\roadrecon\plugins\policies.py", line 248, in _parse_locationcrit
    objects = self._translate_locations(clist)
  File "c:\users\administrator\.virtualenvs\roadtools-ianiaubn\lib\site-packages\roadtools\roadrecon\plugins\policies.py", line 261, in _translate_locations
    if detaildata['KnownNetworkPolicies']['NetworkId'] in locs:
KeyError: 'KnownNetworkPolicies'
```

Mind taking a look? :)

Regards,
Mariusz.

**Comment by mgeeky** [comment]
Ah shiet, sorry about that - I was using an older release. The most recent one has that fixed already.

Closing it, sorry!
