### ISSUE TITLE
GUI internal server error

### ISSUE THREAD

**Issue by fl0mb** [dirkjanm/ROADtools#46]
i can not  use the GUI, it is answered with a 500 internal server error.
Apparently a file is missing, maybe i misunderstood the install instructions. I used:

git clone https://github.com/dirkjanm/ROADtools.git 
pip3 install roadlib/
pip3 install roadrecon/

Error Message:
```
─$ roadrecon gui -d roadrecon.db --debug
 * Serving Flask app 'roadtools.roadrecon.server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 733-781-644
127.0.0.1 - - [16/Aug/2022 12:21:41] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/user/.local/lib/python3.10/site-packages/roadtools/roadrecon/server.py", line 157, in get_index
    return send_file('dist_gui/index.html')
  File "/usr/lib/python3/dist-packages/flask/helpers.py", line 612, in send_file
    return werkzeug.utils.send_file(
  File "/usr/lib/python3/dist-packages/werkzeug/utils.py", line 701, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/lib/python3.10/site-packages/roadtools/roadrecon/dist_gui/index.html'

```

**Comment by dirkjanm** [comment]
There is no pre-built version of the gui included in the source code on git. You can either:
* Download a pre-built release from the latest version on Azure Pipelines (current latest version here: https://dev.azure.com/dirkjanm/ROADtools/_build/results?buildId=1037&view=artifacts&pathAsName=false&type=publishedArtifacts)
* Build the gui manually if you have `npm` installed

Instructions for both these steps are in the readme
