### ISSUE TITLE
Error when running gather?

### ISSUE THREAD

**Issue by kafkaesqu3** [dirkjanm/ROADtools#50]
After i auth and run the gather command, I get this error. 

```
Starting data gathering phase 1 of 2 (collecting objects)
Traceback (most recent call last):
  File "/home/user/.local/bin/roadrecon", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/roadtools/roadrecon/main.py", line 119, in main
    gathermain(args)
  File "/home/user/.local/lib/python3.7/site-packages/roadtools/roadrecon/gather.py", line 613, in main
    loop.run_until_complete(run(args))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.7/site-packages/roadtools/roadrecon/gather.py", line 469, in run
    await asyncio.gather(*tasks)
  File "/home/user/.local/lib/python3.7/site-packages/roadtools/roadrecon/gather.py", line 213, in dump_object
    commit(self.engine, dbtype, cache)
  File "/home/user/.local/lib/python3.7/site-packages/roadtools/roadrecon/gather.py", line 157, in commit
    engine.execute(
AttributeError: 'Engine' object has no attribute 'execute
```

I have tried latest version from github and version in pip

**Comment by dirkjanm** [comment]
Could you post a `pip freeze` from your virtual environment (if any) to see what dependency versions you have? sounds like an outdated version of sqlalchemy

**Comment by dirkjanm** [comment]
closing due to inactivity. if you have more info, feel free to reopen
