### ISSUE TITLE
TypeError when running roadrecon pugin policies

### ISSUE THREAD

**Issue by sT0wn-nl** [dirkjanm/ROADtools#54]
After successfully retrieving all azure data, i get the following error when generating the conditional access policies overview:

```
roadrecon plugin policies
Warning: Not all object IDs could be resolved for this policy
Warning: Not all object IDs could be resolved for this policy
Warning: Not all object IDs could be resolved for this policy
Traceback (most recent call last):
  File "/usr/local/bin/roadrecon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/roadtools/roadrecon/main.py", line 125, in main
    plugin_module.main(args)
  File "/usr/local/lib/python3.10/dist-packages/roadtools/roadrecon/plugins/policies.py", line 508, in main
    plugin.main(args.print)
  File "/usr/local/lib/python3.10/dist-packages/roadtools/roadrecon/plugins/policies.py", line 448, in main
    out['who'] = self._parse_who(conditions)
  File "/usr/local/lib/python3.10/dist-packages/roadtools/roadrecon/plugins/policies.py", line 344, in _parse_who
    ucond = cond['Users']
TypeError: 'NoneType' object is not subscriptable
```

I'm running the latest roadrecon in kali installed trough pip.

**Comment by dirkjanm** [comment]
Would you be able to share the policy that breaks by pasting the output from `roadrecon plugin policies -p`? I only need the policy definition for the one that breaks, please redact any names/guids that aren't public.

**Comment by sT0wn-nl** [comment]
Thanks for the response, here is the requested information

```
Default Policy
xxxx-xxx-xxx-xxx-xxxxx
{   'AccessTokenLifetimeTimeSpan': None,
    'CasSessionControlType': None,
    'ClaimsProviders': None,
    'Conditions': None,
    'ContinuousAccessEvaluationMode': None,
    'Controls': None,
    'CreatedDateTime': None,
    'EnforceAllPoliciesForEas': None,
    'IncludeOtherLegacyClientTypeForEvaluation': None,
    'LastUpdatedTimestamp': '2021-04-01T09:46:44.7739012Z',
    'ModifiedDateTime': None,
    'NamespaceIdentifiersToBlockLoginFromUnsupportedClientApplications': None,
    'PersistentBrowserSessionMode': 'NotSet',
    'ResiliencyDefaultsMode': None,
    'SessionControls': None,
    'SignInFrequency': 'NotSet',
    'SignInFrequencyTimeSpan': None,
    'SignInFrequencyType': None,
    'SmartSessionManagementSettings': {   'GroupsToInclude': [],
                                          'IsStrictLocationEnforcementEnabled': False,
                                          'State': 'Enabled',
                                          'UsersToInclude': []},
    'State': 'Disabled',
    'Version': 0}
Traceback (most recent call last):
  File "/usr/local/bin/roadrecon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/roadtools/roadrecon/main.py", line 125, in main
    plugin_module.main(args)
  File "/usr/local/lib/python3.10/dist-packages/roadtools/roadrecon/plugins/policies.py", line 508, in main
    plugin.main(args.print)
  File "/usr/local/lib/python3.10/dist-packages/roadtools/roadrecon/plugins/policies.py", line 448, in main
    out['who'] = self._parse_who(conditions)
  File "/usr/local/lib/python3.10/dist-packages/roadtools/roadrecon/plugins/policies.py", line 344, in _parse_who
    ucond = cond['Users']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by sT0wn-nl** [comment]
Just tested the fix and this solves my problem. Thanks for the action, you rock!
