### ISSUE TITLE
Cryptography>=39 dropping _x509 which breaks the samltoken if using PEM and KEY

### ISSUE THREAD

**Issue by kiwids0220** [dirkjanm/ROADtools#66]
The debug trace for `roadtx samltoken -c ./roadtx_adfs.pem -k ./roadtx_adfs.key .....`
```
Traceback (most recent call last):
  File "/home/kiwi/impacket/bin/roadtx", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kiwi/impacket/lib/python3.11/site-packages/roadtools/roadtx/main.py", line 917, in main
    signed = signer.sign_xml(template, assertionid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiwi/impacket/lib/python3.11/site-packages/roadtools/roadtx/federation.py", line 388, in sign_xml
    signed_xml = signer.sign(data,
                 ^^^^^^^^^^^^^^^^^
  File "/home/kiwi/impacket/lib/python3.11/site-packages/signxml/signer.py", line 239, in sign
    signature_annotator(sig_root, signing_settings=signing_settings)
  File "/home/kiwi/impacket/lib/python3.11/site-packages/signxml/signer.py", line 313, in _add_key_info
    x509_certificate.text = strip_pem_header(dump_certificate(FILETYPE_PEM, cert))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiwi/impacket/lib/python3.11/site-packages/OpenSSL/crypto.py", line 2052, in dump_certificate
    result_code = _lib.PEM_write_bio_X509(bio, cert._x509)
                                               ^^^^^^^^^^
AttributeError: 'cryptography.hazmat.bindings._rust.x509.Certificat' object has no attribute '_x509'
```

Temp Fix (try to use venv when using ROADtools if possible):
```
pip uninstall -y cryptography
pip install 'cryptography<39'
```

**Comment by dirkjanm** [comment]
hey, thanks for the report, I just pushed a fix to git, could you test whether that solves the issue? (it does on my side)

**Comment by kiwids0220** [comment]
Hey, thank for the quick response. I just did a retest and its working with the latest cryptography

**Comment by dirkjanm** [comment]
cool, I'll push it as a bugfix to pypi in a minute
